### ISSUE TITLE
"Weight Cliff" in early version of exported variable font

### ISSUE THREAD

**Issue by thundernixon** [thundernixon/Encode-Sans#2]
## Problem
There is a "weight cliff" when Encode is exported to a VF without edits to the source file:
![encode weight cliff 2018-10-04 at 13 35 44](https://user-images.githubusercontent.com/7355414/46499684-b5245080-c7ee-11e8-9dee-0df71af90e85.gif)

## Probable cause: different values in heavy masters
There are different values for the heaviest weight, between narrow and wide masters. These appear to be derived from the stem widths in these masters.
- Bold Condensed is `193` (stem of `n` is 386 (193*2, in this 2000-UPM font))
- Bold Extended is `232` (stem of `n` is 464 (232*2, in this 2000-UPM font))

This issue is fixed when the VF is generated from a `.designspace` document, with the following changes:
- `<map>` has been commented out
- weight axis values in bold `<source>` files have been set to `900`, the `maximum` value for the axis
- instances have been commented out (they also have weight values outside the specified 100-900 range)
![encode-tempfix 2018-10-04 at 15 54 59](https://user-images.githubusercontent.com/7355414/46499877-590dfc00-c7ef-11e8-853b-5be962b74887.gif)

I need to better understand:
1. What portion of this should be solved in the `.glyphs` font info, vs the tooling (e.g. through the `.designspace` file).
1. How designspace `<map>` values interact with axis inputs and outputs.

**Comment by thundernixon** [comment]
~Turns out, the only problem here was that `<map>` has `input` and `output` values incorrectly swapped. The sources and instances were declared with weight values from 34 to 232, and need to morph to values 100–900. The original code was flipping this.~

~That is, the <axis> for weight looked like this in the designspace:~
```
<!----- incorrect <map> yields bad VF output ------>
<axis default="100" maximum="900" minimum="100" name="Weight" tag="wght">
    <map output="34" input="100" />
    <map output="45" input="275" />
    <map output="62" input="300" />
    <map output="84" input="400" />
    <map output="111" input="500" />
    <map output="141" input="600" />
    <map output="173" input="700" />
    <map output="204" input="800" />
    <map output="232" input="900" />
</axis>
```

~...when it needs to look like this:~

``````
<!----- correct <map> yields good VF output! :) ------>
<axis default="100" maximum="900" minimum="100" name="Weight" tag="wght">
    <map input="34" output="100" />
    <map input="45" output="275" />
    <map input="62" output="300" />
    <map input="84" output="400" />
    <map input="111" output="500" />
    <map input="141" output="600" />
    <map input="173" output="700" />
    <map input="204" output="800" />
    <map input="232" output="900" />
</axis>
```

EDIT: Nevermind, that doesn't fix the issue yet.

**Comment by davelab6** [comment]
If this is still an issue, I suggest to set up a call with Marc or Cosimo to resolve it quickly; no need to grind your gears deducing things known to people in our team :)

**Comment by thundernixon** [comment]
It's been documented more on [FontMake issue 470](https://github.com/googlei18n/fontmake/issues/470). Somehow, kerning classes are getting crossed, seemingly either by FontMake or FontTools. I think it's on Cosimo's to-do list to look at.

**Comment by thundernixon** [comment]
This was solved by a fix to FontTools.
