### ISSUE TITLE
VF labeled instances have incorrect stylenames

### ISSUE THREAD

**Issue by thundernixon** [thundernixon/Encode-Sans#3]
Stylenames don't include width descriptions.
![image](https://user-images.githubusercontent.com/7355414/46501161-adff4180-c7f2-11e8-90a8-09945fbe7c90.png)

This is partly because the designspace doesn't have correct stylenames declared in instances. For example, the instance with axis values and file naming for a "SemiBold Condensed" style simply has `stylename="SemiBold"`

![image](https://user-images.githubusercontent.com/7355414/46501277-01718f80-c7f3-11e8-9e60-f94d3bf57299.png)

However, this is a generated designspace document, so it probably is an issue in the Glyphs file setup, or potentially in FontMake. I'll know more when I can better understand how the data is transformed into a designspace document.

**Comment by thundernixon** [comment]
In the original Glyphs file, instances do not contain full values for their `Style Name`. This is likely the root cause of the issue.

![image](https://user-images.githubusercontent.com/7355414/46502923-5911fa00-c7f7-11e8-9a19-36f0afed255a.png)

**Comment by thundernixon** [comment]
Could also be related to the generated designspace having 
- `stylemapfamilyname="Encode Sans SemiCondensed ExtraLight"` (with a weight and width style name on the family, rather than just the family name)
- `stylemapstylename="regular"` on all instances

![image](https://user-images.githubusercontent.com/7355414/46504933-66ca7e00-c7fd-11e8-9658-3a5b6a103e1c.png)
etc

**Comment by thundernixon** [comment]
The `<map>` _is_ working to morph weight values to the 100–900, based on the fact that leaving the `<map>` and changing a heavy value to `900` gives the following error:

```
AssertionError: Location for axis 'Weight' (mapped to 1568.0) out of range for 'Encode Sans Condensed Black' [100.0..900.0]
```

**Comment by thundernixon** [comment]
When these values are edited in the designspace and used to run FontProject, it does correct the style naming (though weirdly, the ordering of these names doesn't match with my expectations):

![image](https://user-images.githubusercontent.com/7355414/46507149-1c4cff80-c805-11e8-8d1e-1c5b7103397e.png)

**Comment by davelab6** [comment]
> In the original Glyphs file, instances do not contain full values for their Style Name. This is likely the root cause of the issue.

I guess that's because they have an instance Custom Parameter to set the family name, to output correct static instances.

I guess you might need to go sources to VF to static instances, instead of dual source to VF and source to static instances...

**Comment by thundernixon** [comment]
Sorry, I should have updated this issue, but I do think the instance names are that way in the Glyphs file to output the static instances in different widths.

@mjlagattuta's build scripts had a smart method for a `<name>` patch with `sed`. I've updated this for Encode VF, and it's working much better now! I can export from the same Glyphs source, and the names sort as expected in FontView.

![image](https://user-images.githubusercontent.com/7355414/47311876-e2ec0080-d608-11e8-9e4e-9e4a958816f2.png)

**Comment by davelab6** [comment]
Sweet
