### ISSUE TITLE
Glyphs to potentially fix

### ISSUE THREAD

**Issue by thundernixon** [thundernixon/Encode-Sans#5]
A running list of design problems to re-evaluate.

The most immediate issues jump out from:

```
/r.sc
/s.sc
ẞ
/germandbls.sc
Ţ
/eng.sc
Ł
/lslash.sc 
Ø
ø
ą
ų
/eogonek.sc
₡
₩
```

**Comment by thundernixon** [comment]
`/r.sc` has a too-thin right leg in the light masters (especially in the light wide)
![image](https://user-images.githubusercontent.com/7355414/46970918-8c227c00-d088-11e8-80b1-59db12c9d00b.png)
![image](https://user-images.githubusercontent.com/7355414/46970922-90e73000-d088-11e8-9eac-3087e54b1ca0.png)

`/s.sc` looks like it's "leaning back" in the bold narrow master
![image](https://user-images.githubusercontent.com/7355414/46970931-980e3e00-d088-11e8-8c84-5594938e9b2b.png)

`ẞ` & `/germandbls.sc` have a very strange form, and I doubt Germans would feel good about this. Asking some friends.
![image](https://user-images.githubusercontent.com/7355414/46971001-c8ee7300-d088-11e8-9573-9a01ed3ed0e0.png)

`Ţ` & `/eng.sc` have little bits of mismatching outlines in light masters
![image](https://user-images.githubusercontent.com/7355414/46971146-2da9cd80-d089-11e8-84b7-b0398185f6d6.png)
![image](https://user-images.githubusercontent.com/7355414/46971209-57fb8b00-d089-11e8-9a60-4284afa82891.png)

`Ł`, `/lslash.sc`, `Ø`, & `ø` don't follow the logic of any other diagonals in the family
![image](https://user-images.githubusercontent.com/7355414/46971223-634eb680-d089-11e8-9175-1dc8eac4e641.png)

Ogonek doesn't flow into some of the bold letters as well as it could.
![image](https://user-images.githubusercontent.com/7355414/46971284-92652800-d089-11e8-9818-ec26a46445a8.png)
![image](https://user-images.githubusercontent.com/7355414/46971316-a6108e80-d089-11e8-8d09-cb7286f2e6b7.png)

`₡` & `₩` could have less breakage to their bars

![image](https://user-images.githubusercontent.com/7355414/46971395-d2c4a600-d089-11e8-8b92-d8b2f4ef8d64.png)
![image](https://user-images.githubusercontent.com/7355414/46971423-e40db280-d089-11e8-9b37-ff1ae1d59efe.png)
![image](https://user-images.githubusercontent.com/7355414/46971428-e7a13980-d089-11e8-9b35-03414a453fa2.png)
![image](https://user-images.githubusercontent.com/7355414/46971434-ea9c2a00-d089-11e8-8dda-4192372aec57.png)

The design seems to be intentionally avoiding changes to glyph forms between styles, but the `₩`could take an approach similar to IBM Plex (with partial breaks) and would probably be more recognizable.

**Comment by davelab6** [comment]
Would be great to set up time with @fonthausen to go over these

Jacques is coming to NYC 10/31 - 11/3rd or so, if you want to wait until he's here in person :)

**Comment by thundernixon** [comment]
That would be great! I'll plan for that.

**Comment by Fonthausen** [comment]
Cool !

**Comment by thundernixon** [comment]
After talking with Jacques, we concluded that:

- [x] Yes, make the `/R` leg a bit thicker
- [x] Try an alternate form of the `/Germandbls`, but keep the slight bend in the top part (similar to R, B, etc)
- [x] fix the interpolation issue of the `/Enj`, but leave the `/Tcedilla`
- [x] Update the diagonal accents to have sharp, vertical/horizontal terminations
- [x] make the ogonek `/E` smoother, then reduce the little notch by decomposing the lowercase base letters
- [ ] maybe experiment with alternative currency symbols, using GSUB to swap to disconnected versions for bolder weights
